[2023-12-10 19:30:42,622] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2023-12-10 19:30:43,309] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2023-12-10 19:30:43,530] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:30:43,656] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-10 19:30:43,804] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:30:44,283] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2022-08-29 00:00:00+00:00
[2023-12-10 19:30:44,365] {standard_task_runner.py:52} INFO - Started process 485 to run task
[2023-12-10 19:30:44,390] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2022-08-29T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmp30y96kli', '--error-file', '/tmp/tmpzzza02aa']
[2023-12-10 19:30:44,569] {standard_task_runner.py:80} INFO - Job 89: Subtask segunda_tarea
[2023-12-10 19:30:46,495] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-08-29T00:00:00+00:00 [running]> on host 42828894a739
[2023-12-10 19:30:47,652] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2022-08-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-29T00:00:00+00:00
[2023-12-10 19:30:47,698] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 19:30:47,754] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-12-10 19:30:47,902] {subprocess.py:85} INFO - Output:
[2023-12-10 19:30:47,949] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-12-10 19:30:47,961] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-10 19:30:48,420] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20220829T000000, start_date=20231210T193043, end_date=20231210T193048
[2023-12-10 19:30:48,541] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-10 19:30:48,747] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
