[2023-12-10 19:34:49,766] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-11-23T00:00:00+00:00 [queued]>
[2023-12-10 19:34:49,813] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-11-23T00:00:00+00:00 [queued]>
[2023-12-10 19:34:49,823] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:34:49,824] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-10 19:34:49,825] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:34:49,909] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2022-11-23 00:00:00+00:00
[2023-12-10 19:34:49,917] {standard_task_runner.py:52} INFO - Started process 1351 to run task
[2023-12-10 19:34:49,929] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2022-11-23T00:00:00+00:00', '--job-id', '345', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpyqz0ou7x', '--error-file', '/tmp/tmpevm2u0tw']
[2023-12-10 19:34:49,938] {standard_task_runner.py:80} INFO - Job 345: Subtask segunda_tarea
[2023-12-10 19:34:50,475] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-11-23T00:00:00+00:00 [running]> on host 42828894a739
[2023-12-10 19:34:51,666] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2022-11-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-23T00:00:00+00:00
[2023-12-10 19:34:51,683] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 19:34:51,691] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-12-10 19:34:51,816] {subprocess.py:85} INFO - Output:
[2023-12-10 19:34:51,838] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-12-10 19:34:51,839] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-10 19:34:52,168] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20221123T000000, start_date=20231210T193449, end_date=20231210T193452
[2023-12-10 19:34:52,271] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-10 19:34:53,462] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
