[2023-12-10 19:41:45,233] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-04-30T00:00:00+00:00 [queued]>
[2023-12-10 19:41:45,319] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-04-30T00:00:00+00:00 [queued]>
[2023-12-10 19:41:45,349] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:41:45,394] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-10 19:41:45,417] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:41:45,754] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2023-04-30 00:00:00+00:00
[2023-12-10 19:41:45,812] {standard_task_runner.py:52} INFO - Started process 2929 to run task
[2023-12-10 19:41:45,882] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2023-04-30T00:00:00+00:00', '--job-id', '815', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmp3ic727ch', '--error-file', '/tmp/tmpoy2e2atl']
[2023-12-10 19:41:45,935] {standard_task_runner.py:80} INFO - Job 815: Subtask segunda_tarea
[2023-12-10 19:41:47,048] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-04-30T00:00:00+00:00 [running]> on host 42828894a739
[2023-12-10 19:41:48,617] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2023-04-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-30T00:00:00+00:00
[2023-12-10 19:41:48,634] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 19:41:48,635] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-12-10 19:41:48,787] {subprocess.py:85} INFO - Output:
[2023-12-10 19:41:48,794] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-12-10 19:41:48,795] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-10 19:41:49,614] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20230430T000000, start_date=20231210T194145, end_date=20231210T194149
[2023-12-10 19:41:49,953] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-10 19:41:50,675] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
