[2023-12-10 19:43:27,454] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2023-12-10 19:43:27,554] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2023-12-10 19:43:27,571] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:43:27,572] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-10 19:43:27,578] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:43:27,697] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2023-06-12 00:00:00+00:00
[2023-12-10 19:43:27,703] {standard_task_runner.py:52} INFO - Started process 3381 to run task
[2023-12-10 19:43:27,721] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2023-06-12T00:00:00+00:00', '--job-id', '951', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpasywaah7', '--error-file', '/tmp/tmpcj4tfchm']
[2023-12-10 19:43:27,743] {standard_task_runner.py:80} INFO - Job 951: Subtask segunda_tarea
[2023-12-10 19:43:28,721] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-06-12T00:00:00+00:00 [running]> on host 42828894a739
[2023-12-10 19:43:29,295] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2023-06-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-12T00:00:00+00:00
[2023-12-10 19:43:29,300] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 19:43:29,303] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-12-10 19:43:29,333] {subprocess.py:85} INFO - Output:
[2023-12-10 19:43:29,340] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-12-10 19:43:29,341] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-10 19:43:29,610] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20230612T000000, start_date=20231210T194327, end_date=20231210T194329
[2023-12-10 19:43:29,741] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-10 19:43:29,890] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
