[2023-12-10 19:38:14,591] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-02-12T00:00:00+00:00 [queued]>
[2023-12-10 19:38:14,789] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-02-12T00:00:00+00:00 [queued]>
[2023-12-10 19:38:14,903] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:38:14,977] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-10 19:38:15,075] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:38:15,502] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2023-02-12 00:00:00+00:00
[2023-12-10 19:38:15,532] {standard_task_runner.py:52} INFO - Started process 2184 to run task
[2023-12-10 19:38:15,577] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2023-02-12T00:00:00+00:00', '--job-id', '590', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpjtczn4mb', '--error-file', '/tmp/tmpq52hakso']
[2023-12-10 19:38:15,595] {standard_task_runner.py:80} INFO - Job 590: Subtask segunda_tarea
[2023-12-10 19:38:16,291] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-02-12T00:00:00+00:00 [running]> on host 42828894a739
[2023-12-10 19:38:17,431] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2023-02-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-12T00:00:00+00:00
[2023-12-10 19:38:17,440] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 19:38:17,457] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-12-10 19:38:17,597] {subprocess.py:85} INFO - Output:
[2023-12-10 19:38:17,606] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-12-10 19:38:17,630] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-10 19:38:18,005] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20230212T000000, start_date=20231210T193814, end_date=20231210T193818
[2023-12-10 19:38:18,284] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-10 19:38:18,821] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
