[2023-12-10 19:43:59,426] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-06-29T00:00:00+00:00 [queued]>
[2023-12-10 19:43:59,679] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-06-29T00:00:00+00:00 [queued]>
[2023-12-10 19:43:59,688] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:43:59,694] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-10 19:43:59,695] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:43:59,978] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2023-06-29 00:00:00+00:00
[2023-12-10 19:44:00,091] {standard_task_runner.py:52} INFO - Started process 3541 to run task
[2023-12-10 19:44:00,163] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2023-06-29T00:00:00+00:00', '--job-id', '999', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmp3lfkog09', '--error-file', '/tmp/tmpjnio34f5']
[2023-12-10 19:44:00,174] {standard_task_runner.py:80} INFO - Job 999: Subtask segunda_tarea
[2023-12-10 19:44:00,787] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-06-29T00:00:00+00:00 [running]> on host 42828894a739
[2023-12-10 19:44:01,412] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2023-06-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-29T00:00:00+00:00
[2023-12-10 19:44:01,423] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 19:44:01,433] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-12-10 19:44:01,486] {subprocess.py:85} INFO - Output:
[2023-12-10 19:44:01,493] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-12-10 19:44:01,494] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-10 19:44:01,777] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20230629T000000, start_date=20231210T194359, end_date=20231210T194401
[2023-12-10 19:44:01,850] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-10 19:44:02,055] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
