[2023-12-10 19:35:45,777] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-12-14T00:00:00+00:00 [queued]>
[2023-12-10 19:35:45,978] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-12-14T00:00:00+00:00 [queued]>
[2023-12-10 19:35:46,017] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:35:46,041] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-10 19:35:46,074] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:35:46,476] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2022-12-14 00:00:00+00:00
[2023-12-10 19:35:46,588] {standard_task_runner.py:52} INFO - Started process 1583 to run task
[2023-12-10 19:35:46,636] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2022-12-14T00:00:00+00:00', '--job-id', '414', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpfg8t31u3', '--error-file', '/tmp/tmpni537qax']
[2023-12-10 19:35:46,729] {standard_task_runner.py:80} INFO - Job 414: Subtask segunda_tarea
[2023-12-10 19:35:47,558] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2022-12-14T00:00:00+00:00 [running]> on host 42828894a739
[2023-12-10 19:35:48,573] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2022-12-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-14T00:00:00+00:00
[2023-12-10 19:35:48,583] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 19:35:48,585] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-12-10 19:35:48,738] {subprocess.py:85} INFO - Output:
[2023-12-10 19:35:48,758] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-12-10 19:35:48,779] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-10 19:35:49,110] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20221214T000000, start_date=20231210T193545, end_date=20231210T193549
[2023-12-10 19:35:49,215] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-10 19:35:49,541] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
