[2023-12-10 19:38:57,543] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-03-02T00:00:00+00:00 [queued]>
[2023-12-10 19:38:57,775] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-03-02T00:00:00+00:00 [queued]>
[2023-12-10 19:38:57,780] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:38:57,781] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-10 19:38:57,782] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:38:58,083] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2023-03-02 00:00:00+00:00
[2023-12-10 19:38:58,104] {standard_task_runner.py:52} INFO - Started process 2351 to run task
[2023-12-10 19:38:58,180] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2023-03-02T00:00:00+00:00', '--job-id', '644', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmp7s3lt_h5', '--error-file', '/tmp/tmp52g6067t']
[2023-12-10 19:38:58,193] {standard_task_runner.py:80} INFO - Job 644: Subtask segunda_tarea
[2023-12-10 19:38:59,007] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-03-02T00:00:00+00:00 [running]> on host 42828894a739
[2023-12-10 19:39:00,964] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T00:00:00+00:00
[2023-12-10 19:39:00,971] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 19:39:00,982] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-12-10 19:39:01,132] {subprocess.py:85} INFO - Output:
[2023-12-10 19:39:01,172] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-12-10 19:39:01,209] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-10 19:39:02,160] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20230302T000000, start_date=20231210T193857, end_date=20231210T193902
[2023-12-10 19:39:02,326] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-10 19:39:03,572] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
