[2023-12-10 19:42:06,085] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-05-05T00:00:00+00:00 [queued]>
[2023-12-10 19:42:06,135] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-05-05T00:00:00+00:00 [queued]>
[2023-12-10 19:42:06,138] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:42:06,140] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-12-10 19:42:06,142] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-12-10 19:42:06,426] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): segunda_tarea> on 2023-05-05 00:00:00+00:00
[2023-12-10 19:42:06,560] {standard_task_runner.py:52} INFO - Started process 3019 to run task
[2023-12-10 19:42:06,585] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'segunda_tarea', 'scheduled__2023-05-05T00:00:00+00:00', '--job-id', '839', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmp4854ipey', '--error-file', '/tmp/tmpyjqogh7q']
[2023-12-10 19:42:06,668] {standard_task_runner.py:80} INFO - Job 839: Subtask segunda_tarea
[2023-12-10 19:42:08,648] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.segunda_tarea scheduled__2023-05-05T00:00:00+00:00 [running]> on host 42828894a739
[2023-12-10 19:42:10,429] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DavidBU
AIRFLOW_CTX_DAG_ID=mi_primer_dag_v3
AIRFLOW_CTX_TASK_ID=segunda_tarea
AIRFLOW_CTX_EXECUTION_DATE=2023-05-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-05-05T00:00:00+00:00
[2023-12-10 19:42:10,437] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-10 19:42:10,438] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo hola, soy la tarea 2 y sere corrida luego de la Tarea 1']
[2023-12-10 19:42:10,496] {subprocess.py:85} INFO - Output:
[2023-12-10 19:42:10,514] {subprocess.py:92} INFO - hola, soy la tarea 2 y sere corrida luego de la Tarea 1
[2023-12-10 19:42:10,519] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-10 19:42:10,987] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=mi_primer_dag_v3, task_id=segunda_tarea, execution_date=20230505T000000, start_date=20231210T194206, end_date=20231210T194210
[2023-12-10 19:42:11,204] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-10 19:42:12,030] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
